version: "3"

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Konfigurasi untuk menggunakan GPU NVIDIA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # Atau bisa menggunakan runtime (untuk Docker Compose versi lama)
    # runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # Pastikan model diunduh saat container dimulai
    entrypoint: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull llama3 &&
             wait"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_API_URL=http://ollama:11434/api/generate
      - OLLAMA_MODEL=llama3
      - PORT=8000
    volumes:
      - ./backend:/app
      - ./data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:
