apiVersion: apps/v1
kind: Deployment
metadata:
  name: dishcovery-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dishcovery-backend
  template:
    metadata:
      labels:
        app: dishcovery-backend
    spec:
      containers:
      - name: dishcovery-backend
        image: dishcovery-backend:latest      
        imagePullPolicy: Never            
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dishcovery-backend-service
spec:
  type: NodePort
  selector:
    app: dishcovery-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
